name: Acknowledge PagerDuty Incidents

on:
  schedule:
    # Run every 25 minutes
    - cron: '*/25 * * * *'

  workflow_dispatch: # Allow manual runs

jobs:
  acknowledge-incidents:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fetch and Acknowledge Incidents
        env:
          SECRETS: ${{ toJson(secrets) }}
          VARS: ${{ toJson(vars) }}
        run: node src/index.js
